### ISSUE TITLE
Undefined Method 'assets_manifest' for ActionView::Base::Class

### ISSUE THREAD

**Issue by jamescgibson** [botandrose/ember-rails-assets#4]
Hello,

I suspect this might be due to me trying to use this gem with rails 3 -  but after following the instructions, upon trying to render my application in development, I receive the following error: 

```
undefined method `assets_manifest' for ActionView::Base:Class
```

Any thoughts? Thanks!

**Comment by botandrose** [comment]
Yes, this gem only works with Rails 4.x at the moment. If you'd like to open a PR to add Rails 3 support, I'd be open to that.

**Comment by jamescgibson** [comment]
I'll see what I can do - in the meantime will open a PR to at least update the README. 

Cheers, and thanks for the help!
