### ISSUE TITLE
Gem is incompatible with Ember 1.9.x

### ISSUE THREAD

**Issue by viniciusalonso** [botandrose/ember-rails-assets#6]
Hello guys,

I'm trying using this gem with : 

| Tool | Version |
| --- | :-: |
| rails | 4.2.1 |
| ember | 1.9.1 |
| ember-data | 1.13.7 |
| handlebars | 2.0.0 |
| jquery | 1.11.2 |

When I use the method `asset-path`, I see the following error:

`Uncaught TypeError: Cannot read property 'helper' of undefined`

This error happen in this line of code:

https://github.com/botandrose/ember-rails-assets/blob/master/app/assets/javascripts/ember-rails-assets.js#L5

Thanks in advance :)

**Comment by botandrose** [comment]
Hi @viniciusalonso , thanks for the report. Version 0.2.0 of `ember-rails-assets` requires Ember 1.13+. If you're still on an older version of Ember, you can use version ~>0.1.0, for the time being. I'll also see if I can't push out another release today that will be compatible with both.

**Comment by viniciusalonso** [comment]
@botandrose thank you very much !

**Comment by botandrose** [comment]
Released v0.2.1

**Comment by viniciusalonso** [comment]
@botandrose I updated the gem in my project. Now is shown a new error message:

`Uncaught Error: Assertion Failed: An error occured while setting up template bindings. Please check "index" template for invalid markup or bindings within HTML comments.`

I checked my code index template and is right. The error disappears when I remove the code below:

``` handlebars
        <img src="{{asset-path "waiter.jpg"}}" class="img-responsive" />
```

**Comment by botandrose** [comment]
I _believe_ that is invalid syntax in ember 1.9. You may have to use
bind-attr.

**Comment by botandrose** [comment]
Did you get this working with pre-HTMLBars syntax? If so, how? I'd like to
add it to the readme.
